// generated by qbg -output pugevent_query.go .; DO NOT EDIT

package backend

import (
	"github.com/favclip/qbg/qbgutils"
	"google.golang.org/appengine/datastore"
)

// PugEventQueryBuilder build query for PugEvent.
type PugEventQueryBuilder struct {
	q              *datastore.Query
	plugin         qbgutils.Plugin
	OrganizationID *PugEventQueryProperty
	Title          *PugEventQueryProperty
	Description    *PugEventQueryProperty
	URL            *PugEventQueryProperty
	StartAt        *PugEventQueryProperty
	EndAt          *PugEventQueryProperty
	CreatedAt      *PugEventQueryProperty
	UpdatedAt      *PugEventQueryProperty
	SchemaVersion  *PugEventQueryProperty
}

// PugEventQueryProperty has property information for PugEventQueryBuilder.
type PugEventQueryProperty struct {
	bldr *PugEventQueryBuilder
	name string
}

// NewPugEventQueryBuilder create new PugEventQueryBuilder.
func NewPugEventQueryBuilder() *PugEventQueryBuilder {
	return NewPugEventQueryBuilderWithKind("PugEvent")
}

// NewPugEventQueryBuilderWithKind create new PugEventQueryBuilder with specific kind.
func NewPugEventQueryBuilderWithKind(kind string) *PugEventQueryBuilder {
	q := datastore.NewQuery(kind)
	bldr := &PugEventQueryBuilder{q: q}
	bldr.OrganizationID = &PugEventQueryProperty{
		bldr: bldr,
		name: "OrganizationID",
	}
	bldr.Title = &PugEventQueryProperty{
		bldr: bldr,
		name: "Title",
	}
	bldr.Description = &PugEventQueryProperty{
		bldr: bldr,
		name: "Description",
	}
	bldr.URL = &PugEventQueryProperty{
		bldr: bldr,
		name: "URL",
	}
	bldr.StartAt = &PugEventQueryProperty{
		bldr: bldr,
		name: "StartAt",
	}
	bldr.EndAt = &PugEventQueryProperty{
		bldr: bldr,
		name: "EndAt",
	}
	bldr.CreatedAt = &PugEventQueryProperty{
		bldr: bldr,
		name: "CreatedAt",
	}
	bldr.UpdatedAt = &PugEventQueryProperty{
		bldr: bldr,
		name: "UpdatedAt",
	}
	bldr.SchemaVersion = &PugEventQueryProperty{
		bldr: bldr,
		name: "SchemaVersion",
	}

	if plugger, ok := interface{}(bldr).(qbgutils.Plugger); ok {
		bldr.plugin = plugger.Plugin()
		bldr.plugin.Init("PugEvent")
	}

	return bldr
}

// Ancestor sets parent key to ancestor query.
func (bldr *PugEventQueryBuilder) Ancestor(parentKey *datastore.Key) *PugEventQueryBuilder {
	bldr.q = bldr.q.Ancestor(parentKey)
	if bldr.plugin != nil {
		bldr.plugin.Ancestor(parentKey)
	}
	return bldr
}

// KeysOnly sets keys only option to query.
func (bldr *PugEventQueryBuilder) KeysOnly() *PugEventQueryBuilder {
	bldr.q = bldr.q.KeysOnly()
	if bldr.plugin != nil {
		bldr.plugin.KeysOnly()
	}
	return bldr
}

// Start setup to query.
func (bldr *PugEventQueryBuilder) Start(cur datastore.Cursor) *PugEventQueryBuilder {
	bldr.q = bldr.q.Start(cur)
	if bldr.plugin != nil {
		bldr.plugin.Start(cur)
	}
	return bldr
}

// Offset setup to query.
func (bldr *PugEventQueryBuilder) Offset(offset int) *PugEventQueryBuilder {
	bldr.q = bldr.q.Offset(offset)
	if bldr.plugin != nil {
		bldr.plugin.Offset(offset)
	}
	return bldr
}

// Limit setup to query.
func (bldr *PugEventQueryBuilder) Limit(limit int) *PugEventQueryBuilder {
	bldr.q = bldr.q.Limit(limit)
	if bldr.plugin != nil {
		bldr.plugin.Limit(limit)
	}
	return bldr
}

// Query returns *datastore.Query.
func (bldr *PugEventQueryBuilder) Query() *datastore.Query {
	return bldr.q
}

// Filter with op & value.
func (p *PugEventQueryProperty) Filter(op string, value interface{}) *PugEventQueryBuilder {
	switch op {
	case "<=":
		p.LessThanOrEqual(value)
	case ">=":
		p.GreaterThanOrEqual(value)
	case "<":
		p.LessThan(value)
	case ">":
		p.GreaterThan(value)
	case "=":
		p.Equal(value)
	default:
		p.bldr.q = p.bldr.q.Filter(p.name+" "+op, value) // error raised by native query
	}
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, op, value)
	}
	return p.bldr
}

// LessThanOrEqual filter with value.
func (p *PugEventQueryProperty) LessThanOrEqual(value interface{}) *PugEventQueryBuilder {
	p.bldr.q = p.bldr.q.Filter(p.name+" <=", value)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, "<=", value)
	}
	return p.bldr
}

// GreaterThanOrEqual filter with value.
func (p *PugEventQueryProperty) GreaterThanOrEqual(value interface{}) *PugEventQueryBuilder {
	p.bldr.q = p.bldr.q.Filter(p.name+" >=", value)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, ">=", value)
	}
	return p.bldr
}

// LessThan filter with value.
func (p *PugEventQueryProperty) LessThan(value interface{}) *PugEventQueryBuilder {
	p.bldr.q = p.bldr.q.Filter(p.name+" <", value)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, "<", value)
	}
	return p.bldr
}

// GreaterThan filter with value.
func (p *PugEventQueryProperty) GreaterThan(value interface{}) *PugEventQueryBuilder {
	p.bldr.q = p.bldr.q.Filter(p.name+" >", value)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, ">", value)
	}
	return p.bldr
}

// Equal filter with value.
func (p *PugEventQueryProperty) Equal(value interface{}) *PugEventQueryBuilder {
	p.bldr.q = p.bldr.q.Filter(p.name+" =", value)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Filter(p.name, "=", value)
	}
	return p.bldr
}

// Asc order.
func (p *PugEventQueryProperty) Asc() *PugEventQueryBuilder {
	p.bldr.q = p.bldr.q.Order(p.name)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Asc(p.name)
	}
	return p.bldr
}

// Desc order.
func (p *PugEventQueryProperty) Desc() *PugEventQueryBuilder {
	p.bldr.q = p.bldr.q.Order("-" + p.name)
	if p.bldr.plugin != nil {
		p.bldr.plugin.Desc(p.name)
	}
	return p.bldr
}
